version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft_server
    ports:
      - "30000:25565"
    environment:
      EULA: "TRUE"                 # Accept the Minecraft EULA
      VERSION: ${VERSION}            # Specify the Minecraft version (e.g., 1.20.1)
      TYPE: ${TYPE}                # Specify the modding platform (e.g., FORGE, FABRIC, VANILLA)
      FORGEVERSION: ${FORGEVERSION}       # Optional, specify Forge version
      MEMORY: ${MEMORY}                 # Set the memory allocation (e.g., 4G for 4GB)
      MAX_PLAYERS: ${MAX_PLAYERS}
      VIEW_DISTANCE: ${VIEW_DISTANCE}
      ONLINE_MODE: ${ONLINE_MODE}
      ALLOW_FLIGHT: ${ALLOW_FLIGHT}
      SERVER_NAME: ${SERVER_NAME}
      FABRIC_LOADER_VERSION: ${FABRIC_LOADER_VERSION}
    volumes:
      - ./server:/data      # Persistent storage for world data, config, mods, etc.
    stdin_open: true
    tty: true

# Optional: Automatically restart the server if it crashes
    restart: unless-stopped

# To add mods, place them in the ./minecraft-data/mods directory after running the server once.
# Ensure Java is compatible with your Minecraft/Forge version.
